apiVersion: v1
kind: Secret

metadata:
  name: mongodb-secret
  namespace: three-tier

type: Opaque

stringData:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: U3Ryb25nUGFzc3dvcmQxMjMh